const users = [
  {
    id: 1,
    name: "Aarav Sharma",
    age: 28,
    bodyType: ["Vata"],
    energyLevels: "Energetic in bursts",
    concerns: ["Poor sleep", "Stress"],
    location: "Pune, India",
    dailyRoutine: "Irregular",
    climate: "Hot and dry",
    digestion: "Irregular or sensitive",
    dietaryRestrictions: ["Vegetarian"],
    activityLevel: "Moderately active",
    mentalState: "Stressed or anxious",
  },
  {
    id: 2,
    name: "Emily Johnson",
    age: 34,
    bodyType: ["Pitta"],
    energyLevels: "High and steady",
    concerns: ["Skin issues"],
    location: "Austin, USA",
    dailyRoutine: "Regular",
    climate: "Hot and humid",
    digestion: "Strong and regular",
    dietaryRestrictions: ["No specific restrictions"],
    activityLevel: "Very active",
    mentalState: "Calm and balanced",
  },
  {
    id: 3,
    name: "Rohan Mehta",
    age: 42,
    bodyType: ["Kapha"],
    energyLevels: "Low and sluggish",
    concerns: ["Weight management", "Frequent colds"],
    location: "London, UK",
    dailyRoutine: "Irregular",
    climate: "Cold and damp",
    digestion: "Slow and heavy",
    dietaryRestrictions: ["Gluten-free"],
    activityLevel: "Sedentary",
    mentalState: "Unmotivated or heavy",
  },
  {
    id: 4,
    name: "Sophia Lee",
    age: 25,
    bodyType: ["Pitta", "Vata"],
    energyLevels: "Fluctuates unpredictably",
    concerns: ["Stress", "Digestive issues"],
    location: "Seoul, South Korea",
    dailyRoutine: "Regular",
    climate: "Moderate",
    digestion: "Frequently bloated or acidic",
    dietaryRestrictions: ["Vegan"],
    activityLevel: "Moderately active",
    mentalState: "Restless or scattered",
  },
  {
    id: 5,
    name: "Kabir Singh",
    age: 30,
    bodyType: ["Kapha"],
    energyLevels: "Low and sluggish",
    concerns: ["Weight management"],
    location: "Delhi, India",
    dailyRoutine: "Irregular",
    climate: "Hot and dry",
    digestion: "Slow and heavy",
    dietaryRestrictions: ["No specific restrictions"],
    activityLevel: "Sedentary",
    mentalState: "Unmotivated or heavy",
  },
  {
    id: 6,
    name: "Mia Martinez",
    age: 36,
    bodyType: ["Pitta"],
    energyLevels: "High and steady",
    concerns: ["Skin issues", "Stress"],
    location: "Madrid, Spain",
    dailyRoutine: "Regular",
    climate: "Hot and dry",
    digestion: "Strong and regular",
    dietaryRestrictions: ["Vegetarian"],
    activityLevel: "Very active",
    mentalState: "Calm and balanced",
  },
  {
    id: 7,
    name: "Ethan Brown",
    age: 29,
    bodyType: ["Vata"],
    energyLevels: "Energetic in bursts",
    concerns: ["Poor sleep"],
    location: "Toronto, Canada",
    dailyRoutine: "Irregular",
    climate: "Cold and dry",
    digestion: "Irregular or sensitive",
    dietaryRestrictions: ["Gluten-free"],
    activityLevel: "Moderately active",
    mentalState: "Stressed or anxious",
  },
  {
    id: 8,
    name: "Priya Nair",
    age: 31,
    bodyType: ["Kapha", "Pitta"],
    energyLevels: "Low and sluggish",
    concerns: ["Weight management", "Skin issues"],
    location: "Kochi, India",
    dailyRoutine: "Regular",
    climate: "Hot and humid",
    digestion: "Slow and heavy",
    dietaryRestrictions: ["Lactose intolerant"],
    activityLevel: "Sedentary",
    mentalState: "Unmotivated or heavy",
  },
  {
    id: 9,
    name: "Lucas Kim",
    age: 27,
    bodyType: ["Vata"],
    energyLevels: "Fluctuates unpredictably",
    concerns: ["Stress", "Digestive issues"],
    location: "San Francisco, USA",
    dailyRoutine: "Irregular",
    climate: "Moderate",
    digestion: "Irregular or sensitive",
    dietaryRestrictions: ["Vegan"],
    activityLevel: "Moderately active",
    mentalState: "Restless or scattered",
  },
  {
    id: 10,
    name: "Ananya Gupta",
    age: 40,
    bodyType: ["Kapha"],
    energyLevels: "Low and sluggish",
    concerns: ["Frequent colds", "Digestive issues"],
    location: "Chandigarh, India",
    dailyRoutine: "Regular",
    climate: "Cold and damp",
    digestion: "Slow and heavy",
    dietaryRestrictions: ["No specific restrictions"],
    activityLevel: "Sedentary",
    mentalState: "Unmotivated or heavy",
  },
  {
    id: 11,
    name: "Noah Davis",
    age: 33,
    bodyType: ["Pitta"],
    energyLevels: "High and steady",
    concerns: ["Stress"],
    location: "New York, USA",
    dailyRoutine: "Irregular",
    climate: "Cold and dry",
    digestion: "Strong and regular",
    dietaryRestrictions: ["Vegetarian"],
    activityLevel: "Very active",
    mentalState: "Stressed or anxious",
  },
  {
    id: 12,
    name: "Aisha Khan",
    age: 24,
    bodyType: ["Vata", "Kapha"],
    energyLevels: "Fluctuates unpredictably",
    concerns: ["Poor sleep", "Stress"],
    location: "Dubai, UAE",
    dailyRoutine: "Irregular",
    climate: "Hot and dry",
    digestion: "Irregular or sensitive",
    dietaryRestrictions: ["No specific restrictions"],
    activityLevel: "Moderately active",
    mentalState: "Restless or scattered",
  },
  {
    id: 13,
    name: "William Scott",
    age: 45,
    bodyType: ["Kapha"],
    energyLevels: "Low and sluggish",
    concerns: ["Weight management"],
    location: "Melbourne, Australia",
    dailyRoutine: "Regular",
    climate: "Moderate",
    digestion: "Slow and heavy",
    dietaryRestrictions: ["Lactose intolerant"],
    activityLevel: "Sedentary",
    mentalState: "Unmotivated or heavy",
  },
  {
    id: 14,
    name: "Isha Verma",
    age: 29,
    bodyType: ["Pitta"],
    energyLevels: "High and steady",
    concerns: ["Skin issues"],
    location: "Jaipur, India",
    dailyRoutine: "Regular",
    climate: "Hot and dry",
    digestion: "Strong and regular",
    dietaryRestrictions: ["Vegetarian"],
    activityLevel: "Very active",
    mentalState: "Calm and balanced",
  },
  {
    id: 15,
    name: "Daniel Wilson",
    age: 38,
    bodyType: ["Vata"],
    energyLevels: "Energetic in bursts",
    concerns: ["Digestive issues", "Stress"],
    location: "Berlin, Germany",
    dailyRoutine: "Irregular",
    climate: "Cold and damp",
    digestion: "Frequently bloated or acidic",
    dietaryRestrictions: ["Gluten-free"],
    activityLevel: "Moderately active",
    mentalState: "Restless or scattered",
  },
  {
    id: 16,
    name: "Meera Patel",
    age: 35,
    bodyType: ["Kapha"],
    energyLevels: "Low and sluggish",
    concerns: ["Weight management", "Stress"],
    location: "Ahmedabad, India",
    dailyRoutine: "Regular",
    climate: "Hot and dry",
    digestion: "Slow and heavy",
    dietaryRestrictions: ["No specific restrictions"],
    activityLevel: "Sedentary",
    mentalState: "Unmotivated or heavy",
  },
  {
    id: 17,
    name: "Oliver Smith",
    age: 26,
    bodyType: ["Vata", "Pitta"],
    energyLevels: "Energetic in bursts",
    concerns: ["Poor sleep"],
    location: "London, UK",
    dailyRoutine: "Irregular",
    climate: "Cold and damp",
    digestion: "Irregular or sensitive",
    dietaryRestrictions: ["Vegan"],
    activityLevel: "Moderately active",
    mentalState: "Stressed or anxious",
  },
  {
    id: 18,
    name: "Sara Ali",
    age: 32,
    bodyType: ["Pitta"],
    energyLevels: "High and steady",
    concerns: ["Skin issues", "Stress"],
    location: "Karachi, Pakistan",
    dailyRoutine: "Regular",
    climate: "Hot and humid",
    digestion: "Strong and regular",
    dietaryRestrictions: ["Vegetarian"],
    activityLevel: "Very active",
    mentalState: "Calm and balanced",
  },
  {
    id: 19,
    name: "Arjun Desai",
    age: 41,
    bodyType: ["Kapha"],
    energyLevels: "Low and sluggish",
    concerns: ["Weight management", "Digestive issues"],
    location: "Mumbai, India",
    dailyRoutine: "Irregular",
    climate: "Hot and humid",
    digestion: "Slow and heavy",
    dietaryRestrictions: ["Lactose intolerant"],
    activityLevel: "Sedentary",
    mentalState: "Unmotivated or heavy",
  },
  {
    id: 20,
    name: "Chloe Anderson",
    age: 27,
    bodyType: ["Vata"],
    energyLevels: "Fluctuates unpredictably",
    concerns: ["Stress", "Poor sleep"],
    location: "Los Angeles, USA",
    dailyRoutine: "Regular",
    climate: "Moderate",
    digestion: "Frequently bloated or acidic",
    dietaryRestrictions: ["No specific restrictions"],
    activityLevel: "Moderately active",
    mentalState: "Restless or scattered",
  },
];
export default users;
